// Original app copy; these are not attributed quotations from public figures.
export const motivations = [
  [
    "tough",
    "For the ones who built your beginning.",
    "Your parents worked hard to give you choices. Honor that effort with one honest hour today, not another hour spent doubting yourself.",
    "family",
  ],
  [
    "gentle",
    "You are still her.",
    "A hard day does not erase your intelligence. You are strong, you are learning, and you are allowed to begin again.",
    "self",
  ],
  [
    "practical",
    "Make the next step smaller.",
    "Open one missed question. Name the conclusion. Find the gap. You do not have to solve your entire future this afternoon.",
    "study",
  ],
  [
    "tough",
    "Lock in, Angel.",
    "You have given the fear enough of your afternoon. Put the phone down. Open the question. Let your effort speak next.",
    "discipline",
  ],
  [
    "gentle",
    "There is room for you.",
    "You can want a big life and need a small start. Both can be true. Take the small start.",
    "self",
  ],
  [
    "tough",
    "The dream needs your hands.",
    "That law-school acceptance will not be built from wishing. Give the woman you want to become something she can stand on.",
    "future",
  ],
  [
    "practical",
    "Understanding beats collecting hours.",
    "After a question, explain your reasoning in plain words. If you cannot explain it yet, you have found your next useful task.",
    "study",
  ],
  [
    "gentle",
    "You have not run out of chances.",
    "This moment is another place to begin. You do not have to earn a fresh start by feeling worse first.",
    "self",
  ],
  [
    "tough",
    "Turn love into effort.",
    "Think of the early mornings, the sacrifices, the work your family put in. Let that love move your hands toward the page today.",
    "family",
  ],
  [
    "gentle",
    "Their pride can hold more than a number.",
    "Let your love for your family support you. Your worth does not wait for a score report.",
    "family",
  ],
  [
    "tough",
    "A promise to yourself.",
    "I will get a 170. Today, I will back that intention with focused practice, honest review, and the courage to return.",
    "future",
  ],
  [
    "practical",
    "Make tomorrow easier tonight.",
    "Leave your next question, notebook, and first task ready. Give tomorrow’s Angel fewer decisions to make.",
    "study",
  ],
  [
    "gentle",
    "You are capable of learning this.",
    "A question you missed is a place to look more closely. It is not a verdict on your future.",
    "self",
  ],
  [
    "tough",
    "Come back before you feel ready.",
    "Confidence can catch up. Your next study session can start now.",
    "discipline",
  ],
  [
    "gentle",
    "Strong does not mean effortless.",
    "You can feel scared and still do one brave, ordinary thing: try the next question.",
    "self",
  ],
  [
    "practical",
    "Read the argument, not your fear.",
    "Find the conclusion. Mark the support. Ask what must connect them. One reasoning step at a time.",
    "study",
  ],
  [
    "tough",
    "The keys come later.",
    "The car, the office, the life with your name on it. Today’s part is less glamorous: sit down and do the review.",
    "future",
  ],
  [
    "gentle",
    "Rest is allowed here.",
    "You can take a real break without turning it into a trial against yourself. When you return, choose one manageable step.",
    "self",
  ],
  [
    "tough",
    "You said this mattered.",
    "Give it your attention for ten minutes. Not a perfect day. Ten honest minutes. Start there.",
    "discipline",
  ],
  [
    "practical",
    "End with a lesson.",
    "Write one sentence about what you understand better now. Make that the thing you carry into tomorrow.",
    "study",
  ],
  [
    "gentle",
    "My future attorney.",
    "You are more than this test, and you can still give this test your best. There is strength in showing up gently.",
    "future",
  ],
  [
    "tough",
    "Build the proof.",
    "Do not spend the whole day arguing with doubt. Review one mistake so well that tomorrow you will see it coming.",
    "discipline",
  ],
  [
    "gentle",
    "Your pace is not your identity.",
    "Slow progress is still information. Adjust the plan. Ask for help. Keep your place in the story.",
    "self",
  ],
  [
    "practical",
    "A fresh page.",
    "Choose a minimum, standard, or stretch day. Decide what done means before you begin.",
    "study",
  ],
].map(([tone, title, text, theme], i) => ({
  id: `quote-${i}`,
  tone,
  title,
  text,
  theme,
}));
export const personalNotes = [
  {
    id: "love-1",
    title: "My lawyer kuri.",
    text: "My lawyer kuri, you got this. You gone have to save me from my tickets in the future. I’m counting on you 😂",
    sign: "Arsh",
  },
  {
    id: "love-2",
    title: "A little reminder.",
    text: "Lock in, you got this mf. You are strong. You are smart. And I believe in you, even on the days you don’t.",
    sign: "Arsh",
  },
  {
    id: "love-3",
    title: "Before you start doubting.",
    text: "One question at a time, my lawyer kuri. You don’t have to figure out the whole future tonight. Just give yourself a chance today.",
    sign: "Arsh",
  },
  {
    id: "love-4",
    title: "For the hard days.",
    text: "You can have a bad study day and still be my brilliant girl. Take a breath. I’m proud of you for coming back.",
    sign: "Arsh",
  },
  {
    id: "love-5",
    title: "Future me is counting on you.",
    text: "That courtroom is not ready for you. Neither are my future parking tickets. Now go show that practice set what you’re made of.",
    sign: "Arsh, your future client",
  },
];
